# Generated by Django 5.0.4 on 2024-05-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=30, verbose_name='Nombre de categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ubicacion', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos_produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('duracion_estimada', models.IntegerField(verbose_name='Duracion estimada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='Nombre')),
                ('imagen_producto', models.ImageField(null=True, upload_to='productos/', verbose_name='Imagen')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('nit_proveedor', models.IntegerField(verbose_name='Proveedor')),
                ('existencias', models.IntegerField(verbose_name='Existencias')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descricion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'prosuctos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
    ]
